/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import algs.model.IMultiPoint;
import algs.model.nd.Hyperpoint;
import java.io.File;
import java.util.Locale;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author greg
 */
public class GuiFrame extends javax.swing.JFrame {

    /**
     * Creates new form GuiFrame
     */
    public GuiFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        algoChoiceBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LoadButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        XLabel = new javax.swing.JLabel();
        XField = new javax.swing.JTextField();
        YLabel = new javax.swing.JLabel();
        YField = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();
        canvas = new gui.GPanel();
        jLabel3 = new javax.swing.JLabel();
        timeBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algorytm najbliższego sąsiada - testowanie czarnoskrzynkowe");
        setResizable(false);

        algoChoiceBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BruteForce", "KD Drzewo" }));
        algoChoiceBox.setName("algoChoiceBox"); // NOI18N
        algoChoiceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoChoiceBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wyniki"));

        resultArea.setColumns(20);
        resultArea.setRows(8);
        jScrollPane1.setViewportView(resultArea);

        jLabel1.setText("Wybór algorytmu:");

        LoadButton.setText("Wczytaj dane");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        runButton.setText("Wykonaj");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Punkt odniesienia:");

        XLabel.setText("X:");

        XField.setText("0.0000");
        XField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        XField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XFieldActionPerformed(evt);
            }
        });

        YLabel.setText("Y:");

        YField.setText("0.0000");
        YField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        YField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YFieldActionPerformed(evt);
            }
        });

        canvas.setBackground(new java.awt.Color(254, 252, 250));
        canvas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jLabel3.setText("Zbiór danych:");

        timeBox.setText("Mierz czas");
        timeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(523, 523, 523))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(algoChoiceBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(LoadButton)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(runButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(timeBox)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(XLabel)
                        .addGap(1, 1, 1)
                        .addComponent(XField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(YLabel)
                        .addGap(6, 6, 6)
                        .addComponent(YField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(algoChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(XLabel)
                            .addComponent(XField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YLabel)
                            .addComponent(YField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(runButton)
                            .addComponent(timeBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        double[] r = {0.0, 0.0};
        try {
            r[0] = Double.parseDouble(XField.getText());
            r[1] = Double.parseDouble(YField.getText());
        } catch (NumberFormatException e) {
            XField.setText(String.valueOf(0.0000));
            YField.setText(String.valueOf(0.0000));
            r[0] = 0.0;
            r[1] = 0.0;
            resultArea.append("Niewłaściwy format współrzędnych punktu odniesienia. "
                    + "Ustawiam (0,0)\n");
        }
        canvas.setRef(new Hyperpoint(r));
        try {
            if (algoChoiceBox.getSelectedIndex() == 0) {
                canvas.calculateElement("BF", timeBox.isSelected());
                resultArea.append("Metoda BruteForce\n");
            } else {
                canvas.calculateElement("KD", timeBox.isSelected());
                resultArea.append("Metoda KD-drzewo\n");
            }
            resultArea.append("Najbliższy: (" + canvas.nearestx + "," + canvas.nearesty + ")\n");
            resultArea.append("Odległość: " + canvas.dist + "\n");
        } catch (Exception e) {
            resultArea.append(e.toString());
        }
        if (timeBox.isSelected() == true) {
            String opTime = String.format("%.2e", canvas.lastOperationTime);
            resultArea.append("Czas wykonania operacji: " + opTime + "s.\n");
        }

        canvas.repaint();
    }//GEN-LAST:event_runButtonActionPerformed

    private void XFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XFieldActionPerformed

    private void YFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YFieldActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            fileLabel.setText(file.getName());
            try {
                Scanner textfile = new Scanner(file);
                textfile.useLocale(Locale.US);
                nativeItems = new IMultiPoint[textfile.nextInt()];
                System.err.println(nativeItems.length);
                int i = 0;
                while (textfile.hasNextDouble()) {
                    double[] r = {textfile.nextDouble(), textfile.nextDouble()};
                    //System.err.println(r[0]+" "+ r[1]);
                    nativeItems[i] = new Hyperpoint(r);
                    i++;
                }
            } catch (Exception e) {
                Logger.getLogger(GuiFrame.class.getName()).log(Level.SEVERE, null, e);
                resultArea.setText("Nie udało się wczytać pliku " + file.getName());
                fileLabel.setText("");
            }
            canvas.setIPoints(nativeItems);
            canvas.repaint();
        }
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void algoChoiceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoChoiceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algoChoiceBoxActionPerformed

    private void timeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadButton;
    private javax.swing.JTextField XField;
    private javax.swing.JLabel XLabel;
    private javax.swing.JTextField YField;
    private javax.swing.JLabel YLabel;
    private javax.swing.JComboBox algoChoiceBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private gui.GPanel canvas;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton runButton;
    private javax.swing.JCheckBox timeBox;
    // End of variables declaration//GEN-END:variables
    private IMultiPoint[] nativeItems;
}
