/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import algs.model.IMultiPoint;
import algs.model.nd.Hyperpoint;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Locale;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author greg
 */
public class GuiFrame extends javax.swing.JFrame {

    /**
     * Creates new form GuiFrame
     */
    public GuiFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        algoChoiceBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        LoadButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        XLabel = new javax.swing.JLabel();
        XField = new javax.swing.JTextField();
        YLabel = new javax.swing.JLabel();
        YField = new javax.swing.JTextField();
        fileLabel = new javax.swing.JLabel();
        canvas = new gui.GPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algorytm najbliższego sąsiada - testowanie czarnoskrzynkowe");
        setResizable(false);

        algoChoiceBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BruteForce", "KD Drzewo" }));
        algoChoiceBox.setName("algoChoiceBox"); // NOI18N
        algoChoiceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algoChoiceBoxActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Wyniki"));

        resultArea.setColumns(20);
        resultArea.setRows(8);
        jScrollPane1.setViewportView(resultArea);

        jLabel1.setText("Wybór algorytmu:");

        LoadButton.setText("Wczytaj dane");
        LoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadButtonActionPerformed(evt);
            }
        });

        runButton.setText("Wykonaj");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Punkt odniesienia:");

        XLabel.setText("X:");

        XField.setText("0.0000");
        XField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        XField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XFieldActionPerformed(evt);
            }
        });

        YLabel.setText("Y:");

        YField.setText("0.0000");
        YField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        YField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YFieldActionPerformed(evt);
            }
        });

        canvas.setBackground(new java.awt.Color(254, 252, 250));
        canvas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(algoChoiceBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(YField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(XLabel)
                                        .addGap(1, 1, 1)
                                        .addComponent(XField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(YLabel))
                                    .addComponent(jLabel1)
                                    .addComponent(LoadButton)
                                    .addComponent(runButton)
                                    .addComponent(jLabel2))
                                .addGap(0, 97, Short.MAX_VALUE))
                            .addComponent(fileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(canvas, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LoadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(algoChoiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(XLabel)
                            .addComponent(XField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(YLabel)
                            .addComponent(YField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(runButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        double[] r = {Double.parseDouble(XField.getText()), 
                      Double.parseDouble(YField.getText())};
        canvas.setRef(new Hyperpoint(r));
        if(algoChoiceBox.getSelectedIndex() == 0)
            canvas.calculateElement("BF");
        else
            canvas.calculateElement("KD");
        
        resultArea.append("Nearest: ("+canvas.nearestx+","+canvas.nearesty+")\n");
        resultArea.append("Dist: "+canvas.dist+"\n");
        canvas.repaint();
    }//GEN-LAST:event_runButtonActionPerformed

    private void XFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XFieldActionPerformed

    private void YFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YFieldActionPerformed

    private void LoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadButtonActionPerformed
        JFileChooser fc = new JFileChooser();
        int returnVal = fc.showOpenDialog(null);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();

            fileLabel.setText(file.getName());
            try {
                Scanner textfile = new Scanner(file);
                textfile.useLocale(Locale.US);
                nativeItems = new IMultiPoint[textfile.nextInt()];
                System.err.println(nativeItems.length);
                int i=0;
                while (textfile.hasNextDouble()){
                    double[] r = {textfile.nextDouble(), textfile.nextDouble()};
                    System.err.println(r[0]+" "+ r[1]);
                    nativeItems[i] = new Hyperpoint(r);
                    
                    resultArea.append(nativeItems[i]+"\n");
                    i++;
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GuiFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            canvas.setIPoints(nativeItems);
            canvas.repaint();
        }
    }//GEN-LAST:event_LoadButtonActionPerformed

    private void algoChoiceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algoChoiceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algoChoiceBoxActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadButton;
    private javax.swing.JTextField XField;
    private javax.swing.JLabel XLabel;
    private javax.swing.JTextField YField;
    private javax.swing.JLabel YLabel;
    private javax.swing.JComboBox algoChoiceBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private gui.GPanel canvas;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JButton runButton;
    // End of variables declaration//GEN-END:variables
    private IMultiPoint[] nativeItems;
}
